# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build vmn package dev2

on:
#  push:
#    branches: [ wotkflow ]

  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        description: Version type
        options:
        - check
        - patch
        - minor
        required: true


jobs:

  build_pkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

#    - name: Install dependencies
#      run: |
#          sudo apt install -y black
#          python3 -m pip install -r tests/test_requirements.txt
#          python3 -m pip install -r tests/requirements.txt

    - name: build pkg
      run: |
        #make ${{ github.event.inputs.version_type }}
        echo ${{ github.event.inputs.version_type }}
        #make check
        #python3 -m pip install vmn
        #vmn --debug stamp -r patch ron_test 
        #date

#    - name: Publish a Python distribution to PyPI
#      uses: pypa/gh-action-pypi-publish@release/v1
#      with:
#        verbose: true
#        user: __token__
#        password: ${{ secrets.PYPI_API_TOKEN }}
#        print_hash: true
#        skip_existing: false
